name: Build-Test-Deploy
on: [push]  # Here I specified the action (push, pull)
jobs:
  build-tests:
    runs-on: ubuntu-latest # In which machine the image will be created
    steps:
        - name: Checkout React # The name of process
          uses: actions/checkout@v3  # The name of actions(here I specified the branch with React(main))
          with:
            repository: BilVaD1/React_employees_app
            path: repository-a # This is the path to the folder on the virtual machine to the folder with main branch
            ref: main # Name of repository
        - name: Checkout Tests # The name of process
          uses: actions/checkout@v3  # The name of actions(here I specified the branch with tests(Tests))
          with:
            repository: BilVaD1/React_employees_app
            path: repository-b # This is the path to the folder on the virtual machine to the folder with Tests branch
            ref: Tests # Name of repository
        - uses: actions/setup-node@v2 # setup node
          with:
            node-version: 18
        - name: Install from main
          run: |
            cd repository-a
            npm install
        - name: startLocal in main
          run: |
            cd repository-a
            npm run start &
            sleep 6
        - name: Install tests dependencies from Tests branch
          run: |
            cd repository-b
            npm install
        - name: Tests
          run: |
            cd repository-b
            npm run wdio
        - name: Archive Test Results
          if: always() # That means the report will be created every time, whether the Tests step is successful or failed.
          uses: actions/upload-artifact@v3
          with:
            name: allureReport
            path: repository-b/allure-report
        - name: Stop local server
          run: kill $(ps aux | grep '[n]pm' | awk '{print $2}')
  deploy:
    needs: build-tests
    runs-on: ubuntu-latest # In which machine the image will be created
    steps:
        - name: Checkout React # The name of process
          uses: actions/checkout@v3
        - uses: actions/setup-node@v2 # setup node
          with:
            node-version: 18
        #- name: Install
        #  run: npm install # Normal commands 6
        #- name: Deploy
        #  run: npm run deploy