name: Build-Test-Deploy
on: [push]  # Here I specified the action (push, pull)
jobs:
  build:
    runs-on: ubuntu-latest # In which machine the image will be created
    steps:
        - uses: actions/setup-node@v2 # setup node
          with:
            node-version: 18
        - name: Checkout React # The name of process
          uses: actions/checkout@v3  # The name of actions(here I specified the branch with tests)
          with:
            ref: main
            persist-credentials: true
        - name: Install
          run: |
            npm install
        - name: startLocal
          run: |
            npm run start &
            sleep 6
        - name: Checkout Tests # The name of process
          uses: actions/checkout@v3  # The name of actions(here I specified the branch with tests)
          with:
            ref: Tests
            persist-credentials: true
        - name: Install tests npm
          run: npm install # Normal commands
        - name: Test
          run: npm run wdio
        - uses: actions/upload-artifact@v3 # This I use to create the file with reports
          with:
            name: allureReport
            path: ./allure-report
        - name: Stop local server
          run: kill $(ps aux | grep '[n]pm' | awk '{print $2}')
  deploy:
    needs: build
    runs-on: ubuntu-latest # In which machine the image will be created
    steps:
        - uses: actions/setup-node@v2 # setup node
          with:
            node-version: 18
        - name: Install
          run: npm install # Normal commands 6
        - name: Deploy
          run: npm run deploy
