name: Build-Test-Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout 1
          uses: actions/checkout@v3
        - uses: actions/setup-node@v2
          with:
            node-version: 18
        - name: Install
          run: |
            npm install
            npm install -g wait-on
        - name: startLocal
          run: npm run start &
        - name: Wait for the server to start
          run: wait-on http://localhost:8080
        - name: Checkout
          uses: actions/checkout@v3
          with:
            ref: Tests
        - name: Install tests npm
          run: npm install
        - name: Test
          run: npm run wdio
        - uses: actions/upload-artifact@v3
          with:
            name: allureReport
            path: ./allure-report
        - name: Stop local server
          run: kill $(lsof -i :8080 -t)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-node@v2
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Deploy
          run: npm run deploy

